# Generated by Django 5.2.4 on 2025-07-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
