# Generated by Django 5.2.4 on 2025-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
            ],
        ),
    ]
